name: "Github Action: updated gist every week"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * 1"
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          node github.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
