name: "Github Action: updated gist every day"
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* 1/4 * * *"
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Script
        run: |
          node weibo.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
