name: "Github Action: updated gist"
on:
  push:
    branches:
      - master
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      # cron job
      - uses: actions/upload-artifact@v2
      - name: daily
        uses: ./.github/actions/daily.yml
      - name: weekly
        uses: ./.github/actions/weekly.yml
